import type { Workspace } from './domain.ts';

export function createSample(): Workspace {
  return {
    version: 0,
    revision: 0,
    proposals: [],
    audit: [],
    undo: null,
    event: {
      name: 'Common Ground 2026',
      date: '2026-09-19',
      venue: 'Bengaluru',
      timezone: 'Asia/Kolkata',
      start: 540,
      end: 1020,
      turnover: 15,
      breakStart: 780,
      breakEnd: 840,
    },
    rooms: [
      { id: 'auditorium', name: 'The Auditorium', capacity: 400 },
      { id: 'studio', name: 'Studio A', capacity: 180 },
      { id: 'workshop', name: 'The Workshop', capacity: 90 },
    ],
    speakers: [
      { id: 'asha', name: 'Asha Kapoor' },
      { id: 'mira', name: 'Mira Sen' },
      { id: 'arjun', name: 'Arjun Mehta' },
      { id: 'leah', name: 'Leah Park' },
      { id: 'noah', name: 'Noah Ellis' },
      { id: 'zoya', name: 'Zoya Khan' },
      { id: 'dev', name: 'Dev Rao' },
    ],
    sessions: [
      {
        id: 'opening',
        title: 'Opening the common ground',
        speakerIds: ['asha'],
        roomId: 'auditorium',
        start: 540,
        duration: 60,
        attendees: 340,
        type: 'keynote',
        locked: true,
      },
      {
        id: 'motion',
        title: 'Designing for a world in motion',
        speakerIds: ['mira'],
        roomId: 'auditorium',
        start: 630,
        duration: 60,
        attendees: 260,
        type: 'talk',
        locked: false,
      },
      {
        id: 'craft',
        title: 'The craft behind the interface',
        speakerIds: ['noah'],
        roomId: 'auditorium',
        start: 720,
        duration: 60,
        attendees: 280,
        type: 'talk',
        locked: false,
      },
      {
        id: 'future',
        title: 'The future is a team sport',
        speakerIds: ['asha'],
        roomId: 'auditorium',
        start: 840,
        duration: 60,
        attendees: 300,
        type: 'panel',
        locked: false,
      },
      {
        id: 'closing',
        title: 'Until we meet again',
        speakerIds: ['asha'],
        roomId: 'auditorium',
        start: 960,
        duration: 45,
        attendees: 350,
        type: 'keynote',
        locked: true,
      },
      {
        id: 'small-teams',
        title: 'Small teams, bigger possibilities',
        speakerIds: ['arjun'],
        roomId: 'studio',
        start: 615,
        duration: 60,
        attendees: 120,
        type: 'panel',
        locked: false,
      },
      {
        id: 'access',
        title: 'A more accessible internet',
        speakerIds: ['zoya'],
        roomId: 'studio',
        start: 705,
        duration: 60,
        attendees: 150,
        type: 'talk',
        locked: false,
      },
      {
        id: 'trust',
        title: 'Building trust into technology',
        speakerIds: ['noah'],
        roomId: 'studio',
        start: 840,
        duration: 60,
        attendees: 140,
        type: 'talk',
        locked: false,
      },
      {
        id: 'collab',
        title: 'A new kind of collaboration',
        speakerIds: ['mira'],
        roomId: 'studio',
        start: 915,
        duration: 60,
        attendees: 140,
        type: 'talk',
        locked: false,
      },
      {
        id: 'make',
        title: 'Make something that matters',
        speakerIds: ['leah'],
        roomId: 'workshop',
        start: 615,
        duration: 90,
        attendees: 72,
        type: 'workshop',
        locked: false,
      },
      {
        id: 'prototype',
        title: 'Prototyping the possible',
        speakerIds: ['dev'],
        roomId: 'workshop',
        start: 720,
        duration: 60,
        attendees: 80,
        type: 'workshop',
        locked: false,
      },
      {
        id: 'systems',
        title: 'From sketches to systems',
        speakerIds: ['dev'],
        roomId: 'workshop',
        start: 840,
        duration: 90,
        attendees: 80,
        type: 'workshop',
        locked: false,
      },
    ],
    disruptions: [],
  };
}
