import type { Workspace } from './domain.ts';

export function createSample(): Workspace {
  return {
    version: 0,
    revision: 0,
    proposals: [],
    audit: [],
    undo: null,
    event: {
      name: 'Common Ground 2026',
      date: '2026-09-19',
      venue: 'Bengaluru',
      timezone: 'Asia/Kolkata',
      start: 540,
      end: 1020,
      turnover: 15,
      breakStart: 780,
      breakEnd: 840,
    },
    rooms: [
      { id: 'auditorium', name: 'The Auditorium', capacity: 400 },
      { id: 'studio', name: 'Studio A', capacity: 180 },
      { id: 'workshop', name: 'The Workshop', capacity: 90 },
    ],
    speakers: [
      { id: 'asha', name: 'Asha Kapoor' },
      { id: 'mira', name: 'Mira Sen' },
      { id: 'arjun', name: 'Arjun Mehta' },
      { id: 'leah', name: 'Leah Park' },
      { id: 'noah', name: 'Noah Ellis' },
      { id: 'zoya', name: 'Zoya Khan' },
      { id: 'dev', name: 'Dev Rao' },
    ],
    sessions: [
      {
        id: 'opening',
        title: 'Opening the common ground',
        speakerIds: ['asha'],
        roomId: 'auditorium',
        start: 540,
        duration: 60,
        attendees: 340,
        type: 'keynote',
        locked: true,
      },
      {
        id: 'motion',
        title: 'Designing for a world in motion',
        speakerIds: ['mira'],
        roomId: 'auditorium',
        start: 630,
        duration: 60,
        attendees: 260,
        type: 'talk',
        locked: false,
      },
      {
        id: 'craft',
        title: 'The craft behind the interface',
        speakerIds: ['noah'],
        roomId: 'auditorium',
        start: 720,
        duration: 60,
        attendees: 280,
        type: 'talk',
        locked: false,
      },
      {
        id: 'future',
        title: 'The future is a team sport',
        speakerIds: ['asha'],
        roomId: 'auditorium',
        start: 840,
        duration: 60,
        attendees: 300,
        type: 'panel',
        locked: false,
      },
      {
        id: 'closing',
        title: 'Until we meet again',
        speakerIds: ['asha'],
        roomId: 'auditorium',
        start: 960,
        duration: 45,
        attendees: 350,
        type: 'keynote',
        locked: true,
      },
      {
        id: 'small-teams',
        title: 'Small teams, bigger possibilities',
        speakerIds: ['arjun'],
        roomId: 'studio',
        start: 615,
        duration: 60,
        attendees: 120,
        type: 'panel',
        locked: false,
      },
      {
        id: 'access',
        title: 'A more accessible internet',
        speakerIds: ['zoya'],
        roomId: 'studio',
        start: 705,
        duration: 60,
        attendees: 150,
        type: 'talk',
        locked: false,
      },
      {
        id: 'trust',
        title: 'Building trust into technology',
        speakerIds: ['noah'],
        roomId: 'studio',
        start: 840,
        duration: 60,
        attendees: 140,
        type: 'talk',
        locked: false,
      },
      {
        id: 'collab',
        title: 'A new kind of collaboration',
        speakerIds: ['mira'],
        roomId: 'studio',
        start: 915,
        duration: 60,
        attendees: 140,
        type: 'talk',
        locked: false,
      },
      {
        id: 'make',
        title: 'Make something that matters',
        speakerIds: ['leah'],
        roomId: 'workshop',
        start: 615,
        duration: 90,
        attendees: 72,
        type: 'workshop',
        locked: false,
      },
      {
        id: 'prototype',
        title: 'Prototyping the possible',
        speakerIds: ['dev'],
        roomId: 'workshop',
        start: 720,
        duration: 60,
        attendees: 80,
        type: 'workshop',
        locked: false,
      },
      {
        id: 'systems',
        title: 'From sketches to systems',
        speakerIds: ['dev'],
        roomId: 'workshop',
        start: 840,
        duration: 90,
        attendees: 80,
        type: 'workshop',
        locked: false,
      },
    ],
    disruptions: [],
  };
}

export function createCampusSample(): Workspace {
  const sessions: Workspace['sessions'] = [
    {
      id: 'campus-briefing',
      title: 'Campus week briefing',
      speakerIds: ['dean-maya'],
      roomId: 'auditorium',
      start: 540,
      duration: 60,
      attendees: 280,
      type: 'keynote',
      locked: true,
      day: 0,
    },
    {
      id: 'calculus',
      title: 'Engineering calculus',
      speakerIds: ['prof-iyer'],
      roomId: 'lecture-a',
      start: 540,
      duration: 60,
      attendees: 96,
      type: 'talk',
      locked: false,
      day: 0,
    },
    {
      id: 'robotics-lab',
      title: 'Robotics lab',
      speakerIds: ['dr-shah'],
      roomId: 'science-lab',
      start: 660,
      duration: 90,
      attendees: 42,
      type: 'workshop',
      locked: false,
      day: 0,
    },
    {
      id: 'football-practice',
      title: 'Inter-college football practice',
      speakerIds: ['coach-ravi'],
      roomId: 'sports-ground',
      start: 900,
      duration: 90,
      attendees: 55,
      type: 'workshop',
      locked: false,
      day: 0,
    },
    {
      id: 'algorithms',
      title: 'Algorithms and data structures',
      speakerIds: ['prof-nair'],
      roomId: 'lecture-a',
      start: 540,
      duration: 60,
      attendees: 104,
      type: 'talk',
      locked: false,
      day: 1,
    },
    {
      id: 'chemistry-lab',
      title: 'Applied chemistry lab',
      speakerIds: ['dr-shah'],
      roomId: 'science-lab',
      start: 660,
      duration: 90,
      attendees: 38,
      type: 'workshop',
      locked: false,
      day: 1,
    },
    {
      id: 'career-forum',
      title: 'Industry and careers forum',
      speakerIds: ['dean-maya', 'ms-kapoor'],
      roomId: 'auditorium',
      start: 900,
      duration: 75,
      attendees: 310,
      type: 'panel',
      locked: false,
      day: 1,
    },
    {
      id: 'design-studio',
      title: 'Human-centered design studio',
      speakerIds: ['ms-kapoor'],
      roomId: 'seminar-room',
      start: 540,
      duration: 90,
      attendees: 54,
      type: 'workshop',
      locked: false,
      day: 2,
    },
    {
      id: 'research-colloquium',
      title: 'Student research colloquium',
      speakerIds: ['prof-iyer', 'prof-nair'],
      roomId: 'auditorium',
      start: 660,
      duration: 75,
      attendees: 210,
      type: 'panel',
      locked: false,
      day: 2,
    },
    {
      id: 'athletics-meet',
      title: 'Athletics meet',
      speakerIds: ['coach-ravi'],
      roomId: 'sports-ground',
      start: 840,
      duration: 120,
      attendees: 420,
      type: 'workshop',
      locked: true,
      day: 2,
    },
    {
      id: 'systems',
      title: 'Distributed systems',
      speakerIds: ['prof-nair'],
      roomId: 'lecture-a',
      start: 600,
      duration: 60,
      attendees: 88,
      type: 'talk',
      locked: false,
      day: 3,
    },
    {
      id: 'innovation-clinic',
      title: 'Innovation project clinic',
      speakerIds: ['ms-kapoor'],
      roomId: 'seminar-room',
      start: 690,
      duration: 60,
      attendees: 48,
      type: 'workshop',
      locked: false,
      day: 3,
    },
    {
      id: 'cultural-rehearsal',
      title: 'Cultural festival rehearsal',
      speakerIds: ['ananya'],
      roomId: 'auditorium',
      start: 900,
      duration: 90,
      attendees: 180,
      type: 'workshop',
      locked: false,
      day: 3,
    },
    {
      id: 'physics',
      title: 'Modern physics',
      speakerIds: ['dr-shah'],
      roomId: 'lecture-a',
      start: 540,
      duration: 60,
      attendees: 110,
      type: 'talk',
      locked: false,
      day: 4,
    },
    {
      id: 'club-council',
      title: 'Student club council',
      speakerIds: ['ananya', 'dean-maya'],
      roomId: 'seminar-room',
      start: 660,
      duration: 60,
      attendees: 64,
      type: 'panel',
      locked: false,
      day: 4,
    },
    {
      id: 'weekly-showcase',
      title: 'Weekly campus showcase',
      speakerIds: ['ananya'],
      roomId: 'auditorium',
      start: 900,
      duration: 75,
      attendees: 300,
      type: 'keynote',
      locked: false,
      day: 4,
    },
  ];
  return {
    version: 0,
    revision: 0,
    proposals: [],
    audit: [],
    undo: null,
    event: {
      name: 'Northstar Campus Week',
      date: '2026-09-07',
      venue: 'Fictional university campus',
      timezone: 'Asia/Kolkata',
      start: 480,
      end: 1080,
      turnover: 15,
      breakStart: 780,
      breakEnd: 840,
    },
    rooms: [
      { id: 'auditorium', name: 'Main Auditorium', capacity: 350 },
      { id: 'lecture-a', name: 'Lecture Hall A', capacity: 120 },
      { id: 'science-lab', name: 'Science Lab', capacity: 60 },
      { id: 'sports-ground', name: 'Sports Ground', capacity: 500 },
      { id: 'seminar-room', name: 'Seminar Room', capacity: 70 },
    ],
    speakers: [
      { id: 'dean-maya', name: 'Dean Maya Rao' },
      { id: 'prof-iyer', name: 'Professor Kabir Iyer' },
      { id: 'dr-shah', name: 'Dr Nisha Shah' },
      { id: 'coach-ravi', name: 'Coach Ravi Menon' },
      { id: 'prof-nair', name: 'Professor Leela Nair' },
      { id: 'ms-kapoor', name: 'Meera Kapoor' },
      { id: 'ananya', name: 'Ananya Bose' },
    ],
    sessions,
    disruptions: [],
    recurrence: {
      mode: 'weekly',
      activeWeek: '2026-09-07',
      templateSessions: structuredClone(sessions),
      overrides: [],
    },
  };
}
